server:
  port: 8080
spring:
  application:
    name: "task-list-project"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:postgresql://localhost:5432/notes-db"
    username: "user"
    password: "password"
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
